In [2]:
import numpy as np  #module for manipulating rows and coloumns in a table individually

In [3]:
a=np.arange(15)
b=np.arange(20)

In [4]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
a=np.arange(1,16,1)  #giving the start and end points along with the even space

In [6]:
print(a)
print(len(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
15


In [7]:
a=a.reshape(3,5)    #reshaping the 1D array'a' having 'a'=  (rows,cols)

In [8]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
b = np.array( [1.0, 2.0, 3.0, 4.0] )
print(b)
print(b.dtype)
print(type(b))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [10]:
c = np.eye(10)         #produces identical matric
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
print(c.dtype)

float64


In [13]:
d = np.linspace(-1, 2, 15, endpoint=True)
print(d)

[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [14]:
len(d)

15

In [15]:
d=d.reshape(3,5)

In [16]:
d

array([[-1.        , -0.78571429, -0.57142857, -0.35714286, -0.14285714],
       [ 0.07142857,  0.28571429,  0.5       ,  0.71428571,  0.92857143],
       [ 1.14285714,  1.35714286,  1.57142857,  1.78571429,  2.        ]])

In [17]:
e=np.logspace(-1,3,5,endpoint=True,base=10)

In [18]:
e

array([1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

In [19]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [20]:
f = np.fromfunction(lambda i, j: i == j, (2, 3), dtype=float)
print(f)
print(f.dtype)

[[ True False False]
 [False  True False]]
bool


In [21]:
help(np.fromfunction)

Help on function fromfunction in module numpy:

fromfunction(function, shape, **kwargs)
    Construct an array by executing a function over each coordinate.
    
    The resulting array therefore has a value ``fn(x, y, z)`` at
    coordinate ``(x, y, z)``.
    
    Parameters
    ----------
    function : callable
        The function is called with N parameters, where N is the rank of
        `shape`.  Each parameter represents the coordinates of the array
        varying along a specific axis.  For example, if `shape`
        were ``(2, 2)``, then the parameters would be
        ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
    shape : (N,) tuple of ints
        Shape of the output array, which also determines the shape of
        the coordinate arrays passed to `function`.
    dtype : data-type, optional
        Data-type of the coordinate arrays passed to `function`.
        By default, `dtype` is float.
    
    Returns
    -------
    fromfunction : any
        The 

In [22]:
a=np.arange(9).reshape(3,3)

In [23]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
a=a*a
print(a)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [25]:
a=a/2

In [26]:
a

array([[ 0. ,  0.5,  2. ],
       [ 4.5,  8. , 12.5],
       [18. , 24.5, 32. ]])

In [27]:
b=a.transpose()

In [28]:
b

array([[ 0. ,  4.5, 18. ],
       [ 0.5,  8. , 24.5],
       [ 2. , 12.5, 32. ]])

In [29]:
a@b

array([[   4.25,   29.  ,   76.25],
       [  29.  ,  240.5 ,  677.  ],
       [  76.25,  677.  , 1948.25]])

In [66]:
c=np.arange(1,10,1).reshape(3,3)

In [67]:
print(c)
c.sum(axis=0)   #summing the rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [68]:
c.sum()

45

In [69]:
print(c.max(),c.min())

9 1


In [70]:
b = a*np.pi/12.0
print(b)

[[0.         0.13089969 0.52359878]
 [1.17809725 2.0943951  3.27249235]
 [4.71238898 6.414085   8.37758041]]


In [71]:
print(c)
f=np.sin(c)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [72]:
e=f+c

In [73]:
print(e)

[[1.84147098 2.90929743 3.14112001]
 [3.2431975  4.04107573 5.7205845 ]
 [7.6569866  8.98935825 9.41211849]]


In [77]:
s=np.arange(12)

In [78]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
s[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
s[2:6]

array([2, 3, 4, 5])

In [82]:
s[::-1]     #printing in a reverse order

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [83]:
s[::-2]  #sking alternative element

array([11,  9,  7,  5,  3,  1])

In [86]:
s[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
m=np.arange(10,19,1)
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [91]:
m=m.reshape(3,3)

In [95]:
m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [96]:
print(m[0,0])

10


In [98]:
print(m[0:2,0:2])

[[10 11]
 [13 14]]


In [100]:
m[:,1]

array([11, 14, 17])

In [101]:
n=m.flatten()
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [102]:
for r in m:
    print(r)

[10 11 12]
[13 14 15]
[16 17 18]


In [103]:
for n in m.flat:
    print(n)

10
11
12
13
14
15
16
17
18


In [104]:
n=m


In [109]:
n is m

True

In [113]:
a = np.arange(12)
c = a[:]
a.shape = (3,4)
print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [114]:
a = np.arange(12)
a.shape = (3,4)
c = a[:]
print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [115]:
c[2][1]=20
print(c)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 20 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 20 10 11]]


In [117]:
a[a>7]=1
print(a)

[[0 1 2 3]
 [4 5 6 7]
 [1 1 1 1]]


In [120]:
a[a == 0] = 1
a

array([[1, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 1, 1, 1]])

In [122]:
a == 1   #returns bool value True or False

array([[ True,  True, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [126]:
a[np.logical_and(a > 3, a <= 9)] = 0.0
a[np.logical_or(a==2,a==3)]=1

In [127]:
a

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

In [128]:
a==1

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])