In [1]:
import numpy as np

In [2]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, M, endpoint=False)
y = np.linspace(ymin, ymax, N, endpoint=True)

print(x.shape)
print(y.shape)
print(x)
y

(32,)
(64,)
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]


array([0.        , 0.01587302, 0.03174603, 0.04761905, 0.06349206,
       0.07936508, 0.0952381 , 0.11111111, 0.12698413, 0.14285714,
       0.15873016, 0.17460317, 0.19047619, 0.20634921, 0.22222222,
       0.23809524, 0.25396825, 0.26984127, 0.28571429, 0.3015873 ,
       0.31746032, 0.33333333, 0.34920635, 0.36507937, 0.38095238,
       0.3968254 , 0.41269841, 0.42857143, 0.44444444, 0.46031746,
       0.47619048, 0.49206349, 0.50793651, 0.52380952, 0.53968254,
       0.55555556, 0.57142857, 0.58730159, 0.6031746 , 0.61904762,
       0.63492063, 0.65079365, 0.66666667, 0.68253968, 0.6984127 ,
       0.71428571, 0.73015873, 0.74603175, 0.76190476, 0.77777778,
       0.79365079, 0.80952381, 0.82539683, 0.84126984, 0.85714286,
       0.87301587, 0.88888889, 0.9047619 , 0.92063492, 0.93650794,
       0.95238095, 0.96825397, 0.98412698, 1.        ])

In [3]:
print(len(x))
print(len(y))

32
64


In [4]:
import time

In [5]:
M = 32
N = 64

x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(0.0, 1.0, N, endpoint=False)

In [6]:
t0=time.time()
g=np.zeros((M,N))
for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1=time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.014908552169799805 s


In [10]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [11]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0009605884552001953 s


In [13]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [19]:
e=np.eye(9, dtype=np.int16)

In [21]:
len(e)
print(e)

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]


In [24]:
np.zeros(9, dtype='int64').reshape(3,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [32]:
x = np.arange(9).reshape(3,3)
y = np.eye(3)
print(x)
print(y)
np.concatenate([y,x])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [34]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
np.concatenate([a,b])

array([1. , 2. , 3. , 4. , 5. , 1.1, 2.2, 3.3, 4.4, 5.5])

In [35]:
e = np.array([1, 2, 3, 4])
f = np.array([4, 3, 2])
np.concatenate([f,e])

array([4, 3, 2, 1, 2, 3, 4])

In [38]:
z = [9, 4, 6]
print(np.concatenate([e, f, z]))

[1 2 3 4 4 3 2 9 4 6]


In [41]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [43]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [51]:
x = [1, 2, 3, 4, 5, 6 ,7, 8, 9, 10,11,12 ]
a, b, c,d = np.split(x, [3,6,9])
print(a,b,c,d)

[1 2 3] [4 5 6] [7 8 9] [10 11 12]


In [57]:
horizontal = np.arange(1,17,1).reshape((4, 4))
horizontal

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
h1,h2=np.hsplit(horizontal,[2])
print(h1)
print(h2)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [66]:
v1,v2=np.vsplit(horizontal,[2])
print(v1)
print(v2)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [68]:
x = np.arange(1, 9)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [74]:
x = np.arange(1, 9)
print(x)
np.multiply.reduce(x)

[1 2 3 4 5 6 7 8]


40320

In [75]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [77]:
np.subtract.accumulate(x)

array([  1,  -1,  -4,  -8, -13, -19, -26, -34], dtype=int32)

In [78]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)